name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Get Dependencies
        run: flutter pub get

      - name: Generate iOS Files (Fix Podfile Error)
        run: flutter build ios --no-codesign

      - name: Update Pod Repository
        run: pod repo update
        working-directory: ios

      - name: Install CocoaPods Dependencies
        run: pod install --verbose
        working-directory: ios

      - name: Build iOS App (No Codesign)
        run: flutter build ios --release --no-codesign

      - name: Create Payload Directory
        run: mkdir -p Payload
        working-directory: build/ios/iphoneos

      - name: Move App into Payload
        run: mv Runner.app Payload
        working-directory: build/ios/iphoneos

      - name: Zip Payload to IPA
        run: zip -qq -r FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload IPA to GitHub Releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
